// Llama Manager Flasher — unit tests for manifest normalization.
//
// Copyright (c) 2026 Doubling Technologies (DoubTech.ai). Use of this file is
// governed by the LICENSE file in the repository root.
//
// Verifies that both upstream release-description formats (AMD SHA256SUMS
// text and NVIDIA Spark release.json) normalize into the shared
// ApplianceImage shape, and that every malformed variant (missing entries,
// bad hashes, bad sizes, wrong types) is rejected with ManifestError rather
// than yielding a descriptor that could flash a wrong or unverifiable image.

import { describe, it, expect } from 'vitest';
import {
  parseAmdSha256Sums,
  parseSparkRelease,
  ManifestError,
} from '../src/shared/manifest';

const AMD_BASE = 'https://llama-manager.doubtech.ai/downloads';
const SPARK_BASE = 'https://llama-manager.doubtech.ai/downloads-nvidia-spark';
const SHA = '999f7906e0148477fa6c2f853e320ac19702be44b19ef55477ecb313b973f61a';

describe('parseAmdSha256Sums', () => {
  it('normalizes a single-line SHA256SUMS file', () => {
    const img = parseAmdSha256Sums(
      `${SHA}  llama-manager-ubuntu-24.04.4-amd64.iso\n`,
      AMD_BASE,
    );
    expect(img).toEqual({
      platformId: 'amd',
      arch: 'amd64',
      channel: 'stable',
      version: '24.04.4',
      file: 'llama-manager-ubuntu-24.04.4-amd64.iso',
      url: `${AMD_BASE}/llama-manager-ubuntu-24.04.4-amd64.iso`,
      sha256: SHA,
      size: null,
    });
  });

  it('tolerates comments, blank lines, and unrelated entries', () => {
    const text = [
      '# generated by release pipeline',
      '',
      `${'a'.repeat(64)}  something-else.img.xz`,
      `${SHA.toUpperCase()}  llama-manager-ubuntu-25.10.1-amd64.iso`,
    ].join('\n');
    const img = parseAmdSha256Sums(text, `${AMD_BASE}/`);
    expect(img.version).toBe('25.10.1');
    expect(img.sha256).toBe(SHA); // lowercased
    expect(img.url).toBe(`${AMD_BASE}/llama-manager-ubuntu-25.10.1-amd64.iso`);
  });

  it('rejects an empty file', () => {
    expect(() => parseAmdSha256Sums('', AMD_BASE)).toThrow(ManifestError);
  });

  it('rejects a truncated hash', () => {
    expect(() =>
      parseAmdSha256Sums(`${SHA.slice(0, 40)}  llama-manager-ubuntu-24.04.4-amd64.iso`, AMD_BASE),
    ).toThrow(ManifestError);
  });

  it('rejects a file with no matching amd64 iso entry', () => {
    expect(() =>
      parseAmdSha256Sums(`${SHA}  llama-manager-ubuntu-24.04.4-arm64.iso`, AMD_BASE),
    ).toThrow(ManifestError);
  });
});

describe('parseSparkRelease', () => {
  const valid = {
    platform: 'nvidia-spark',
    arch: 'arm64',
    channel: 'experimental',
    version: '24.04.4',
    artifacts: [
      {
        file: 'llama-manager-ubuntu-24.04.4-nvidia-spark-arm64-EXPERIMENTAL.iso',
        sha256: 'bdbf554966bdee78963efdbe5c7847978132d12f078dc4bb7609373933d5e5db',
        size: 10411048960,
      },
    ],
  };

  it('normalizes a valid release.json', () => {
    const img = parseSparkRelease(valid, SPARK_BASE);
    expect(img).toEqual({
      platformId: 'nvidia-spark',
      arch: 'arm64',
      channel: 'experimental',
      version: '24.04.4',
      file: valid.artifacts[0].file,
      url: `${SPARK_BASE}/${valid.artifacts[0].file}`,
      sha256: valid.artifacts[0].sha256,
      size: 10411048960,
    });
  });

  it('prefers the first .iso artifact when several artifacts exist', () => {
    const doc = {
      ...valid,
      artifacts: [
        { file: 'notes.txt', sha256: 'c'.repeat(64), size: 12 },
        ...valid.artifacts,
      ],
    };
    expect(parseSparkRelease(doc, SPARK_BASE).file).toBe(valid.artifacts[0].file);
  });

  it('defaults an unknown channel to experimental', () => {
    expect(parseSparkRelease({ ...valid, channel: 'weird' }, SPARK_BASE).channel).toBe(
      'experimental',
    );
  });

  it('rejects a non-object document', () => {
    expect(() => parseSparkRelease(null, SPARK_BASE)).toThrow(ManifestError);
    expect(() => parseSparkRelease('nope', SPARK_BASE)).toThrow(ManifestError);
  });

  it('rejects a document with no artifacts', () => {
    expect(() => parseSparkRelease({ ...valid, artifacts: [] }, SPARK_BASE)).toThrow(
      ManifestError,
    );
    const { artifacts: _omitted, ...noArtifacts } = valid;
    expect(() => parseSparkRelease(noArtifacts, SPARK_BASE)).toThrow(ManifestError);
  });

  it('rejects an artifact with a malformed sha256', () => {
    const doc = { ...valid, artifacts: [{ ...valid.artifacts[0], sha256: 'zz' }] };
    expect(() => parseSparkRelease(doc, SPARK_BASE)).toThrow(ManifestError);
  });

  it('rejects an artifact with a non-positive or missing size', () => {
    const zero = { ...valid, artifacts: [{ ...valid.artifacts[0], size: 0 }] };
    expect(() => parseSparkRelease(zero, SPARK_BASE)).toThrow(ManifestError);
    const missing = { ...valid, artifacts: [{ file: 'a.iso', sha256: 'a'.repeat(64) }] };
    expect(() => parseSparkRelease(missing, SPARK_BASE)).toThrow(ManifestError);
  });

  it('rejects a document with no version', () => {
    expect(() => parseSparkRelease({ ...valid, version: '' }, SPARK_BASE)).toThrow(
      ManifestError,
    );
  });
});
